import type { ChecklistSection } from "./types";

/**
 * TwinKit 0.6.0 migration map — discover → pack → unpack → verify.
 * Times are rough human effort, not pure download time.
 */
export const SECTIONS: ChecklistSection[] = [
  {
    id: "pack-discover",
    title: "Discover (primary Mac)",
    blurb: "Inventory reality before you pack folklore.",
    phase: "pack",
    modules: ["core"],
    encouragements: [
      "Discovery first. Memory is a liar; find is a friend.",
      "If INVENTORY.json is empty of agents, you're packing the wrong machine.",
    ],
    items: [
      {
        id: "pack-download-discover",
        title: "Download twin-discover.sh from Toolkit",
        detail: "Writes INVENTORY.json with tools, flags, Daylight-ish paths, skill names.",
        minutes: 1,
        kind: "download",
        modules: ["core"],
        phases: ["pack"],
      },
      {
        id: "pack-run-discover",
        title: "Run twin-discover.sh on the primary Mac",
        detail: "Creates ~/Desktop/twinkit-discover-*/ with INVENTORY.json + .md.",
        minutes: 3,
        kind: "script",
        modules: ["core"],
        phases: ["pack"],
        command: "bash ~/Downloads/twin-discover.sh",
      },
      {
        id: "pack-import-inventory",
        title: "Import INVENTORY.json in TwinKit Toolkit",
        detail: "Auto-toggles modules from what was actually found. Skim the notes line.",
        minutes: 2,
        kind: "manual",
        modules: ["core"],
        phases: ["pack"],
        hint: "Toolkit → Sync & discover → Import inventory",
      },
    ],
  },
  {
    id: "pack-prep",
    title: "Pack prep",
    blurb: "Close the loop on the machine that already works.",
    phase: "pack",
    modules: ["core", "transfer"],
    encouragements: [
      "Your old Mac still loves you. This is a cloning, not a breakup.",
      "If it feels tedious, good — that means the new Mac will feel magical.",
    ],
    items: [
      {
        id: "pack-disk-space",
        title: "Confirm free disk for the pack archive",
        detail:
          "Claude configs are tiny. Android trees are not. Prefer external SSD if unsure.",
        minutes: 2,
        kind: "manual",
        modules: ["core"],
        phases: ["pack"],
      },
      {
        id: "pack-download-script",
        title: "Download twin-pack.sh from Toolkit",
        detail:
          "Pack 0.6: secret scan (fail-closed), redacted shell rc, no cp -R fallback, progress.json scaffold.",
        minutes: 1,
        kind: "download",
        modules: ["core"],
        phases: ["pack"],
      },
      {
        id: "pack-run-script",
        title: "Run twin-pack.sh (must exit 0)",
        detail:
          "Exit 2 means secret scan hits — fix SECRETS_REPORT.md or explicitly allow after review.",
        minutes: 10,
        kind: "script",
        modules: ["core"],
        phases: ["pack"],
        command: "bash ~/Downloads/twin-pack.sh",
        hint: "Optional: TWINKIT_INVENTORY=~/Desktop/twinkit-discover-*/INVENTORY.json",
      },
      {
        id: "pack-review-secrets",
        title: "Read SECRETS_REPORT.md and THREAT_MODEL.md",
        detail:
          "Zero hits is not a guarantee. Treat the pack as sensitive config.",
        minutes: 5,
        kind: "verify",
        modules: ["core"],
        phases: ["pack"],
      },
      {
        id: "pack-review-manifest",
        title: "Skim MANIFEST.md + notes/HUMAN.md",
        detail: "Fill human auth methods and DC1 smoke steps before you unplug.",
        minutes: 5,
        kind: "manual",
        modules: ["core", "claude"],
        phases: ["pack"],
      },
      {
        id: "pack-export-progress",
        title: "Export progress.json from TwinKit into the pack folder",
        detail:
          "Toolkit → Export progress.json → save over the scaffold in the pack. Cross-machine source of truth.",
        minutes: 2,
        kind: "download",
        modules: ["core", "transfer"],
        phases: ["pack"],
      },
    ],
  },
  {
    id: "pack-claude",
    title: "Pack Claude Code brain",
    blurb: "Skills, MCP, settings — the stuff that makes Claude feel like yours.",
    phase: "pack",
    modules: ["claude"],
    encouragements: [
      "This folder is your Claude personality. Guard it like a houseplant.",
      "Skills travel. API keys do not — re-auth on the other side.",
    ],
    items: [
      {
        id: "pack-claude-dir",
        title: "Confirm ~/.claude packed (credentials excluded)",
        detail: "rsync-only; if rsync missing, pack fails closed (install rsync).",
        minutes: 3,
        kind: "verify",
        modules: ["claude"],
        phases: ["pack"],
        command: "ls -la ~/.claude",
      },
      {
        id: "pack-claude-md",
        title: "Grab global + project CLAUDE.md paths you care about",
        detail: "Paths listed in notes/claude-md-paths.txt when mdfind works.",
        minutes: 4,
        kind: "manual",
        modules: ["claude"],
        phases: ["pack"],
      },
      {
        id: "pack-claude-mcp",
        title: "Export MCP server list / secret names (not values)",
        detail: "Document each MCP; secrets stay in 1Password.",
        minutes: 6,
        kind: "manual",
        modules: ["claude"],
        phases: ["pack"],
      },
      {
        id: "pack-claude-auth-note",
        title: "Note Claude Code auth method",
        detail: "Subscription vs API — you will re-login. No keys in the archive.",
        minutes: 2,
        kind: "auth",
        modules: ["claude"],
        phases: ["pack"],
      },
    ],
  },
  {
    id: "pack-codex",
    title: "Pack Codex",
    blurb: "OpenAI Codex CLI config notes.",
    phase: "pack",
    modules: ["codex"],
    encouragements: ["Two CLIs, one desk energy. Pack both or you'll miss the sibling."],
    items: [
      {
        id: "pack-codex-config",
        title: "Confirm Codex config paths packed",
        detail: "Typically ~/.codex — auth files excluded by glob.",
        minutes: 3,
        kind: "verify",
        modules: ["codex"],
        phases: ["pack"],
        command: "ls -la ~/.codex 2>/dev/null; which codex",
      },
      {
        id: "pack-codex-auth",
        title: "Note Codex auth method",
        detail: "ChatGPT or API — re-sign-in on the new machine.",
        minutes: 2,
        kind: "auth",
        modules: ["codex"],
        phases: ["pack"],
      },
    ],
  },
  {
    id: "pack-tooling",
    title: "Pack wired CLIs",
    blurb: "Grok Build, Muse Spark, brew inventory.",
    phase: "pack",
    modules: ["grok", "muse", "core"],
    encouragements: ["If Claude can spawn it, pack a note about it."],
    items: [
      {
        id: "pack-grok-cli",
        title: "Capture Grok Build CLI install + wiring",
        detail: "Binary, auth, skill/MCP invocation.",
        minutes: 5,
        kind: "manual",
        modules: ["grok"],
        phases: ["pack"],
        command: "which grok; grok --version 2>/dev/null; type grok",
      },
      {
        id: "pack-muse",
        title: "Capture Muse Spark install + version pin",
        detail: "Note 1.2.x if skills assume it.",
        minutes: 5,
        kind: "manual",
        modules: ["muse"],
        phases: ["pack"],
      },
      {
        id: "pack-brewfile",
        title: "Confirm Brewfile in pack",
        detail: "twin-pack dumps brew bundle when Homebrew exists.",
        minutes: 2,
        kind: "verify",
        modules: ["core"],
        phases: ["pack"],
      },
    ],
  },
  {
    id: "pack-android-daylight",
    title: "Pack Android + Daylight DC1",
    blurb: "Heavyweight toolchains and device lore.",
    phase: "pack",
    modules: ["android", "daylight"],
    encouragements: [
      "Gradle is the final boss of disk space.",
      "DC1 tools are tribal knowledge — write smoke steps down.",
    ],
    items: [
      {
        id: "pack-android-env",
        title: "Confirm ANDROID_HOME / JAVA_HOME captured",
        detail: "In android/env-and-packages.txt (values may be empty if unset in non-interactive shell).",
        minutes: 4,
        kind: "verify",
        modules: ["android"],
        phases: ["pack"],
        command: 'echo "ANDROID_HOME=$ANDROID_HOME"; echo "JAVA_HOME=$JAVA_HOME"',
      },
      {
        id: "pack-android-sdk-decide",
        title: "Decide: reinstall SDK vs selective copy",
        detail: "Same arch + fast SSD may copy; otherwise reinstall is cleaner.",
        minutes: 5,
        kind: "manual",
        modules: ["android"],
        phases: ["pack"],
      },
      {
        id: "pack-gradle-note",
        title: "Confirm gradle.properties redacted into pack",
        detail: "Caches intentionally skipped.",
        minutes: 3,
        kind: "verify",
        modules: ["android"],
        phases: ["pack"],
      },
      {
        id: "pack-daylight-tools",
        title: "Confirm Daylight/DC1 trees in pack/daylight",
        detail: "Discover + find hits; .env and keystores excluded.",
        minutes: 10,
        kind: "manual",
        modules: ["daylight"],
        phases: ["pack"],
      },
      {
        id: "pack-daylight-smoke-notes",
        title: "Write DC1 smoke steps into HUMAN.md",
        detail: "Unpack will not invent your device ritual.",
        minutes: 5,
        kind: "manual",
        modules: ["daylight"],
        phases: ["pack"],
      },
    ],
  },
  {
    id: "pack-secrets-transfer",
    title: "Secrets & transfer",
    blurb: "Never put API keys in the zip. Move identity safely.",
    phase: "pack",
    modules: ["ssh", "transfer", "chrome"],
    encouragements: [
      "Secrets travel via 1Password, not USB sticky notes.",
      "The archive is a recipe, not a vault.",
    ],
    items: [
      {
        id: "pack-1password",
        title: "Confirm password manager has all agent tokens",
        detail: "Claude, OpenAI, GitHub, Grok, Muse — not only Keychain folklore.",
        minutes: 5,
        kind: "auth",
        modules: ["ssh"],
        phases: ["pack"],
      },
      {
        id: "pack-ssh-decide",
        title: "Plan SSH key strategy",
        detail: "Prefer new keys on new Mac. Private keys are never packed.",
        minutes: 4,
        kind: "manual",
        modules: ["ssh"],
        phases: ["pack"],
      },
      {
        id: "pack-transfer-media",
        title: "Copy pack folder to transfer media",
        detail: "FileVault SSD or age/gpg tarball. Not unencrypted email.",
        minutes: 10,
        kind: "manual",
        modules: ["transfer"],
        phases: ["pack"],
      },
      {
        id: "pack-chrome-note",
        title: "List required Chrome extensions + accounts",
        detail: "Claude, Codex, password manager.",
        minutes: 3,
        kind: "manual",
        modules: ["chrome"],
        phases: ["pack"],
      },
    ],
  },

  // UNPACK
  {
    id: "unpack-os",
    title: "New Mac foundation",
    blurb: "Fresh machine, same brain. OS oxygen first.",
    phase: "unpack",
    modules: ["core"],
    encouragements: [
      "Updates first. Your future self hates half-updated CLIs.",
      "Name the machine something you won't regret shouting across the house.",
    ],
    items: [
      {
        id: "unpack-name-mac",
        title: "Name the Mac + optional iCloud",
        detail: "iCloud helps Keychain/Find My; not required for Claude Code.",
        minutes: 5,
        kind: "manual",
        modules: ["core"],
        phases: ["unpack"],
      },
      {
        id: "unpack-updates",
        title: "Install macOS updates and reboot once",
        detail: "Rough estimate — wall clock varies. Start big downloads early.",
        minutes: 15,
        kind: "manual",
        modules: ["core"],
        phases: ["unpack"],
        hint: "Times are rough, not promises.",
      },
      {
        id: "unpack-xcode-clt",
        title: "Install Xcode Command Line Tools",
        detail: "git, compilers, many brew formulae.",
        minutes: 8,
        kind: "script",
        modules: ["core"],
        phases: ["unpack"],
        command: "xcode-select --install",
      },
      {
        id: "unpack-homebrew",
        title: "Install Homebrew",
        detail: "Package manager everything else hangs off.",
        minutes: 8,
        kind: "script",
        modules: ["core"],
        phases: ["unpack"],
        command:
          '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"',
      },
      {
        id: "unpack-rsync",
        title: "Ensure rsync is available",
        detail: "Unpack refuses recursive cp fallbacks for safety.",
        minutes: 2,
        kind: "script",
        modules: ["core"],
        phases: ["unpack"],
        command: "brew install rsync || which rsync",
      },
    ],
  },
  {
    id: "unpack-shell",
    title: "Shell + runtimes",
    blurb: "Make the terminal feel like home before the AI tools arrive.",
    phase: "unpack",
    modules: ["core"],
    encouragements: ["A good .zshrc is a warm blanket."],
    items: [
      {
        id: "unpack-bring-pack",
        title: "Copy twinkit-pack folder onto the new Mac",
        detail: "Keep it until twin-verify is green.",
        minutes: 5,
        kind: "manual",
        modules: ["transfer"],
        phases: ["unpack"],
      },
      {
        id: "unpack-import-progress",
        title: "Import pack progress.json into TwinKit UI",
        detail: "Restores checklist state across machines. Browser localStorage alone is not enough.",
        minutes: 2,
        kind: "manual",
        modules: ["core", "transfer"],
        phases: ["unpack"],
        hint: "Toolkit → Import progress.json",
      },
      {
        id: "unpack-dry-run",
        title: "Optional: twin-unpack.sh --dry-run",
        detail: "See every write without touching disk.",
        minutes: 3,
        kind: "script",
        modules: ["core"],
        phases: ["unpack"],
        command: "bash twin-unpack.sh --dry-run ~/Desktop/twinkit-pack-*",
      },
      {
        id: "unpack-run-script",
        title: "Run twin-unpack.sh for real",
        detail: "Restores configs with backups; brew bundle if present.",
        minutes: 12,
        kind: "script",
        modules: ["core"],
        phases: ["unpack"],
        command: "bash twin-unpack.sh ~/Desktop/twinkit-pack-*",
      },
      {
        id: "unpack-shell-rc",
        title: "Merge *.twinkit-new shell files carefully",
        detail: "Redacted rc may need re-adding env names from password manager.",
        minutes: 8,
        kind: "manual",
        modules: ["core"],
        phases: ["unpack"],
      },
      {
        id: "unpack-node",
        title: "Install Node (match MANIFEST when possible)",
        detail: "Rough time — network dependent.",
        minutes: 6,
        kind: "script",
        modules: ["core"],
        phases: ["unpack"],
        command: "brew install node || brew install fnm",
      },
      {
        id: "unpack-git-identity",
        title: "Set git user.name / user.email",
        detail: "Match primary Mac identity.",
        minutes: 2,
        kind: "script",
        modules: ["ssh"],
        phases: ["unpack"],
        command:
          'git config --global user.name "Your Name" && git config --global user.email "you@example.com"',
      },
    ],
  },
  {
    id: "unpack-ssh",
    title: "SSH + GitHub",
    blurb: "Prove you're you to remote repos.",
    phase: "unpack",
    modules: ["ssh"],
    encouragements: ["New keys on new machines is healthy hygiene."],
    items: [
      {
        id: "unpack-ssh-key",
        title: "Generate SSH key (ed25519)",
        detail: "Private keys were never in the pack.",
        minutes: 4,
        kind: "script",
        modules: ["ssh"],
        phases: ["unpack"],
        command: 'ssh-keygen -t ed25519 -C "you@example.com"',
      },
      {
        id: "unpack-github-auth",
        title: "Add key / sign into GitHub CLI",
        detail: "Human auth required.",
        minutes: 5,
        kind: "auth",
        modules: ["ssh"],
        phases: ["unpack"],
        command: "brew install gh && gh auth login",
      },
      {
        id: "unpack-ssh-test",
        title: "Test git@github.com",
        detail: "Should greet you by username.",
        minutes: 2,
        kind: "verify",
        modules: ["ssh"],
        phases: ["unpack"],
        command: "ssh -T git@github.com",
      },
    ],
  },
  {
    id: "unpack-claude",
    title: "Claude Code online",
    blurb: "The main character arrives.",
    phase: "unpack",
    modules: ["claude"],
    encouragements: [
      "This is the moment the Mini becomes a teammate.",
      "If auth fails once, try again — OAuth is a moody cat.",
    ],
    items: [
      {
        id: "unpack-claude-install",
        title: "Install Claude Code CLI",
        detail: "Prefer the same install method as MANIFEST / primary Mac.",
        minutes: 5,
        kind: "script",
        modules: ["claude"],
        phases: ["unpack"],
        command: "npm install -g @anthropic-ai/claude-code  # or official installer",
      },
      {
        id: "unpack-claude-restore",
        title: "Confirm ~/.claude restored",
        detail: "Skills + settings present; credentials re-auth next.",
        minutes: 4,
        kind: "verify",
        modules: ["claude"],
        phases: ["unpack"],
        command: "ls ~/.claude/skills 2>/dev/null; ls ~/.claude",
      },
      {
        id: "unpack-claude-auth",
        title: "Sign into Claude Code",
        detail: "Human-required OAuth / API flow.",
        minutes: 4,
        kind: "auth",
        modules: ["claude"],
        phases: ["unpack"],
        command: "claude",
      },
      {
        id: "unpack-claude-mcp",
        title: "Re-wire MCP servers that need secrets",
        detail: "Env vars from 1Password; test each once.",
        minutes: 10,
        kind: "manual",
        modules: ["claude"],
        phases: ["unpack"],
      },
      {
        id: "unpack-claude-skill-twinkit",
        title: "Install TwinKit skill into ~/.claude/skills",
        detail: "From Toolkit download — next migration stays conversational.",
        minutes: 3,
        kind: "download",
        modules: ["claude"],
        phases: ["unpack"],
      },
      {
        id: "unpack-claude-smoke",
        title: "Smoke: Claude reads a local file",
        detail: "Confirm tools + project context.",
        minutes: 5,
        kind: "verify",
        modules: ["claude"],
        phases: ["unpack"],
      },
    ],
  },
  {
    id: "unpack-codex",
    title: "Codex online",
    blurb: "Second brain, same desk.",
    phase: "unpack",
    modules: ["codex"],
    encouragements: ["Two CLIs high-five in your PATH."],
    items: [
      {
        id: "unpack-codex-install",
        title: "Install Codex CLI",
        detail: "Match primary method from MANIFEST when possible.",
        minutes: 5,
        kind: "script",
        modules: ["codex"],
        phases: ["unpack"],
        command: "npm install -g @openai/codex  # or brew / official installer",
      },
      {
        id: "unpack-codex-config",
        title: "Confirm Codex config restored",
        detail: "Then re-auth.",
        minutes: 3,
        kind: "verify",
        modules: ["codex"],
        phases: ["unpack"],
      },
      {
        id: "unpack-codex-auth",
        title: "Sign into Codex",
        detail: "Human required.",
        minutes: 4,
        kind: "auth",
        modules: ["codex"],
        phases: ["unpack"],
      },
      {
        id: "unpack-codex-smoke",
        title: "Smoke test Codex on a tiny task",
        detail: "Read a file / propose a patch.",
        minutes: 4,
        kind: "verify",
        modules: ["codex"],
        phases: ["unpack"],
      },
    ],
  },
  {
    id: "unpack-sidekicks",
    title: "Grok + Muse sidekicks",
    blurb: "The supporting cast Claude already expects.",
    phase: "unpack",
    modules: ["grok", "muse"],
    encouragements: ["Don't skip the wire-up."],
    items: [
      {
        id: "unpack-grok",
        title: "Install Grok Build CLI + auth",
        detail: "Restore skill/MCP that shells out to grok.",
        minutes: 8,
        kind: "script",
        modules: ["grok"],
        phases: ["unpack"],
      },
      {
        id: "unpack-muse",
        title: "Install Muse Spark + verify version",
        detail: "Pin if skills assume 1.2.x.",
        minutes: 8,
        kind: "script",
        modules: ["muse"],
        phases: ["unpack"],
        command: "muse --version  # expect 1.2.x if that's your pin",
      },
      {
        id: "unpack-sidekick-claude",
        title: "Confirm Claude Code can invoke sidekicks",
        detail: "Harmless version checks via each tool.",
        minutes: 5,
        kind: "verify",
        modules: ["grok"],
        phases: ["unpack"],
      },
    ],
  },
  {
    id: "unpack-android",
    title: "Android + Gradle",
    blurb: "Heavy lifts. Estimates are rough — network wins arguments.",
    phase: "unpack",
    modules: ["android"],
    encouragements: [
      "Progress bars build character (and Gradle caches).",
      "Coffee is a valid dependency.",
    ],
    items: [
      {
        id: "unpack-jdk",
        title: "Install JDK (Temurin 17/21 per MANIFEST)",
        detail: "Align with AGP needs.",
        minutes: 8,
        kind: "script",
        modules: ["android"],
        phases: ["unpack"],
        command: "brew install --cask temurin@17",
      },
      {
        id: "unpack-android-studio-or-sdk",
        title: "Install Android Studio or command-line SDK",
        detail: "Rough 25m+ depending on bandwidth.",
        minutes: 25,
        kind: "manual",
        modules: ["android"],
        phases: ["unpack"],
      },
      {
        id: "unpack-sdk-packages",
        title: "Install platform-tools / build-tools from MANIFEST notes",
        detail: "Match API levels you actually ship.",
        minutes: 20,
        kind: "script",
        modules: ["android"],
        phases: ["unpack"],
      },
      {
        id: "unpack-gradle-props",
        title: "Restore ~/.gradle/gradle.properties (re-add secrets)",
        detail: "Pack is redacted — re-key signing/mirrors from 1Password.",
        minutes: 5,
        kind: "manual",
        modules: ["android"],
        phases: ["unpack"],
      },
      {
        id: "unpack-android-smoke",
        title: "Smoke: adb devices + assemble a known project",
        detail: "First Gradle run is slow.",
        minutes: 20,
        kind: "verify",
        modules: ["android"],
        phases: ["unpack"],
        command: "adb devices && ./gradlew assembleDebug",
      },
    ],
  },
  {
    id: "unpack-daylight",
    title: "Daylight DC1 tools",
    blurb: "Device-specific reality check.",
    phase: "unpack",
    modules: ["daylight"],
    encouragements: ["If the device shows up in adb, you already won a level."],
    items: [
      {
        id: "unpack-daylight-restore",
        title: "Restore DC1 scripts / mods from pack/daylight",
        detail: "Fix absolute paths.",
        minutes: 10,
        kind: "manual",
        modules: ["daylight"],
        phases: ["unpack"],
      },
      {
        id: "unpack-daylight-trust",
        title: "Trust the device on this Mac",
        detail: "USB debugging prompts / network ADB.",
        minutes: 5,
        kind: "permission",
        modules: ["daylight"],
        phases: ["unpack"],
      },
      {
        id: "unpack-daylight-logging",
        title: "Verify logging pipeline",
        detail: "One standard capture; files land where expected.",
        minutes: 8,
        kind: "verify",
        modules: ["daylight"],
        phases: ["unpack"],
      },
      {
        id: "unpack-daylight-smoke",
        title: "End-to-end DC1 smoke from HUMAN.md",
        detail: "Whatever you wrote on the pack side.",
        minutes: 10,
        kind: "verify",
        modules: ["daylight"],
        phases: ["unpack"],
      },
    ],
  },
  {
    id: "unpack-chrome",
    title: "Browser extensions + logins",
    blurb: "The clicky bits only a human can click.",
    phase: "unpack",
    modules: ["chrome"],
    encouragements: ["Extensions are tiny. Logins are the tax."],
    items: [
      {
        id: "unpack-chrome-install",
        title: "Install Chrome (or browser of record)",
        detail: "Match what extensions require.",
        minutes: 5,
        kind: "manual",
        modules: ["chrome"],
        phases: ["unpack"],
      },
      {
        id: "unpack-ext-claude",
        title: "Install + sign into Claude Chrome extension",
        detail: "Human OAuth.",
        minutes: 4,
        kind: "auth",
        modules: ["chrome"],
        phases: ["unpack"],
      },
      {
        id: "unpack-ext-codex",
        title: "Install + sign into Codex Chrome extension",
        detail: "Human OAuth.",
        minutes: 4,
        kind: "auth",
        modules: ["chrome"],
        phases: ["unpack"],
      },
      {
        id: "unpack-ext-password",
        title: "Install password manager extension + unlock",
        detail: "1Password / Bitwarden / etc.",
        minutes: 4,
        kind: "auth",
        modules: ["chrome"],
        phases: ["unpack"],
      },
    ],
  },
  {
    id: "unpack-permissions",
    title: "macOS permissions",
    blurb: "Computer Use, Accessibility, Screen Recording — trust falls.",
    phase: "unpack",
    modules: ["permissions"],
    encouragements: [
      "Apple will ask 'are you sure?' about twelve times. You are sure.",
      "Toggle, quit app, reopen. Ancient macOS wisdom.",
    ],
    items: [
      {
        id: "unpack-perm-accessibility",
        title: "Enable Accessibility for Terminal / Claude / agent apps",
        detail: "System Settings → Privacy & Security → Accessibility.",
        minutes: 4,
        kind: "permission",
        modules: ["permissions"],
        phases: ["unpack"],
        command:
          "open 'x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility'",
      },
      {
        id: "unpack-perm-screen",
        title: "Enable Screen Recording where needed",
        detail: "Required for many computer-use / screenshot flows.",
        minutes: 3,
        kind: "permission",
        modules: ["permissions"],
        phases: ["unpack"],
        command:
          "open 'x-apple.systempreferences:com.apple.preference.security?Privacy_ScreenCapture'",
      },
      {
        id: "unpack-perm-fda",
        title: "Full Disk Access only if truly needed",
        detail: "Least privilege. Grant carefully.",
        minutes: 3,
        kind: "permission",
        modules: ["permissions"],
        phases: ["unpack"],
      },
      {
        id: "unpack-perm-automation",
        title: "Allow Automation / Apple Events prompts",
        detail: "When Terminal or Claude automates System Events / browsers.",
        minutes: 3,
        kind: "permission",
        modules: ["permissions"],
        phases: ["unpack"],
      },
      {
        id: "unpack-perm-input",
        title: "Input Monitoring if tools control keyboard/mouse",
        detail: "Computer-use stacks often need this.",
        minutes: 3,
        kind: "permission",
        modules: ["permissions"],
        phases: ["unpack"],
      },
      {
        id: "unpack-perm-relaunch",
        title: "Quit + relaunch agent apps after toggles",
        detail: "Privacy grants often need process restart.",
        minutes: 2,
        kind: "manual",
        modules: ["permissions"],
        phases: ["unpack"],
      },
      {
        id: "unpack-perm-verify",
        title: "Verify computer-use / screenshot path once",
        detail: "Benign screenshot or UI click via Claude.",
        minutes: 5,
        kind: "verify",
        modules: ["permissions"],
        phases: ["unpack"],
      },
    ],
  },
  {
    id: "unpack-verify",
    title: "Parity verify",
    blurb: "Prove the twin with twin-verify — not vibes alone.",
    phase: "unpack",
    modules: ["core"],
    encouragements: [
      "Green PARITY.md is better than a confident shrug.",
      "Fails are a gift list, not a moral judgment.",
    ],
    items: [
      {
        id: "unpack-download-verify",
        title: "Download twin-verify.sh",
        detail: "Compares MANIFEST tool presence vs this Mac.",
        minutes: 1,
        kind: "download",
        modules: ["core"],
        phases: ["unpack"],
      },
      {
        id: "unpack-run-verify",
        title: "Run twin-verify.sh against the pack",
        detail: "Writes PARITY.md + PARITY.json. Exit nonzero if fails remain.",
        minutes: 3,
        kind: "script",
        modules: ["core"],
        phases: ["unpack"],
        command: "bash twin-verify.sh ~/Desktop/twinkit-pack-*",
      },
      {
        id: "unpack-read-parity",
        title: "Triage PARITY fails / warns",
        detail: "Install missing tools or accept intentional gaps in the UI.",
        minutes: 10,
        kind: "verify",
        modules: ["core"],
        phases: ["unpack"],
      },
      {
        id: "unpack-export-progress-final",
        title: "Export updated progress.json back into the pack folder",
        detail: "Keeps the pack folder as the multi-day source of truth.",
        minutes: 2,
        kind: "download",
        modules: ["core"],
        phases: ["unpack"],
      },
    ],
  },
  {
    id: "unpack-final",
    title: "Final boss: twin ready",
    blurb: "Open items = 0. Skips only if you accepted gaps. Then yeet.",
    phase: "unpack",
    modules: ["core"],
    encouragements: [
      "You're in the epilogue. Don't skip the checklist credits.",
      "If three smokes pass and parity is green, ship it.",
    ],
    items: [
      {
        id: "unpack-clone-one-repo",
        title: "Clone one real project and open in Claude Code",
        detail: "git clone → claude → simple edit.",
        minutes: 10,
        kind: "verify",
        modules: ["claude"],
        phases: ["unpack"],
      },
      {
        id: "unpack-leave-plugged",
        title: "Power / sleep / remote access as you like",
        detail: "Home Mini: know the tradeoffs before disabling sleep.",
        minutes: 5,
        kind: "manual",
        modules: ["core"],
        phases: ["unpack"],
      },
      {
        id: "unpack-accept-gaps",
        title: "Review deferred skips — accept intentional gaps only",
        detail:
          "Skipped items do not count as done until you Accept gap. Twin online requires zero unaccepted gaps.",
        minutes: 3,
        kind: "manual",
        modules: ["core"],
        phases: ["unpack"],
        hint: "Mission panel → Gaps",
      },
      {
        id: "unpack-backup-note",
        title: "Calendar: re-discover + re-pack in ~90 days",
        detail: "Setups drift.",
        minutes: 2,
        kind: "manual",
        modules: ["core"],
        phases: ["unpack"],
      },
      {
        id: "unpack-yeet",
        title: "Celebrate and yeet TwinKit UI",
        detail: "Only when twin ready (all checked or accepted gaps). Skill stays on disk.",
        minutes: 1,
        kind: "manual",
        modules: ["core"],
        phases: ["unpack"],
      },
    ],
  },
];
